#include <stdio.h>
#include <sys/socket.h>
#include <stdlib.h>
#include <netinet/in.h>
#include <string.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <openssl/aes.h>
#include <openssl/rand.h>
#include "aes_ctr.h"
#define PORT 8080

struct ctr_state
{
    unsigned char ivec[16];
    unsigned int num;
    unsigned char ecount[16];
};

size_t count;
char *buffer;
AES_KEY key;

int bytes_read, bytes_written;
unsigned char indata[AES_BLOCK_SIZE];
unsigned char outdata[AES_BLOCK_SIZE];
unsigned char ckey[] = "afifgantengbnget"; // It is 128bits though..
unsigned char iv[8] = {0};                 //This should be generated by RAND_Bytes I will take into    consideration your previous post
struct ctr_state state;
int length;
uint8_t file_buffer[AES_BLOCK_SIZE] = {0};
struct sockaddr_in server_address;

int sock, valread, opt = 1, addrlen = sizeof(server_address);
FILE *fileptr;

int init_ctr(struct ctr_state *state, const unsigned char iv[8]);
void decrypt();

int main(int argc, char const *argv[])
{
    if (argc < 2)
    {
        puts("File name not specified");
        exit(EXIT_FAILURE);
    }

    fileptr = fopen(argv[1], "wb");
    if (!fileptr)
    {
        puts("File cannot be opened!");
        exit(EXIT_FAILURE);
    }

    if ((sock = socket(AF_INET, SOCK_STREAM, 0)) < 0)
    {
        printf("\n Socket creation error \n");
        return -1;
    }

    memset(&server_address, '0', sizeof(server_address));

    server_address.sin_family = AF_INET;
    server_address.sin_port = htons(PORT);

    if (inet_pton(AF_INET, "127.0.0.1", &server_address.sin_addr) <= 0)
    {
        printf("\nInvalid address/ Address not supported \n");
        return -1;
    }

    if (connect(sock, (struct sockaddr *)&server_address, sizeof(server_address)) < 0)
    {
        printf("\nConnection Failed \n");
        return -1;
    }

    decrypt();

    close(sock);
    fclose(fileptr);
    return 0;
}

int init_ctr(struct ctr_state *state, const unsigned char iv[8])
{
    state->num = 0;
    memset(state->ecount, 0, 16);
    memset(state->ivec + 8, 0, 8);
    memcpy(state->ivec, iv, 8);
}

void decrypt()
{
    //Opening files where text cipher text is read and the plaintext recovered
    if (fileptr == NULL)
    {
        fputs("File error", stderr);
        exit(1);
    }

    //Initializing the encryption KEY
    AES_set_encrypt_key(ckey, 128, &key);

    //Encrypting Blocks of 16 bytes and writing the output.txt with ciphertext
    init_ctr(&state, iv); //Counter call
    while ((length = recv(sock, file_buffer, AES_BLOCK_SIZE, 0)) > 0)
    {
        AES_ctr128_encrypt(file_buffer, outdata, length, &key, state.ivec, state.ecount, &state.num);
        bytes_written = fwrite(outdata, 1, length, fileptr);
        puts(file_buffer);
    }
    // fclose(fileptr);
    // free(buffer);
}
